spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:usersapi
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
server:
   port: 8080
security:
  jwt:
    token:
      secret-key: secret-key